#!/bin/bash

echo "🏗️ Docusaurus Static Rendering Explanation"
echo "=========================================="
echo ""

echo "📁 How Static Build Works:"
echo "  1. Docusaurus reads docusaurus.config.ts"
echo "  2. Sees i18n.locales: ['en', 'es', 'de', 'fr', 'pt', 'zh', 'ar']"
echo "  3. English is default → no prefix"
echo "  4. Other locales → get prefix (/es/, /de/, etc.)"
echo ""

echo "📂 Build Directory Structure:"
echo "  build/"
echo "  ├── index.html                    # Root redirect"
echo "  ├── documentation/                 # English (default)"
echo "  │   ├── index.html"
echo "  │   ├── intro/"
echo "  │   │   └── index.html"
echo "  │   └── assets/"
echo "  ├── es/                           # Spanish"
echo "  │   ├── documentation/"
echo "  │   │   ├── index.html"
echo "  │   │   ├── intro/"
echo "  │   │   │   └── index.html"
echo "  │   │   └── assets/"
echo "  │   └── index.html"
echo "  ├── de/                           # German"
echo "  │   └── documentation/"
echo "  │       ├── index.html"
echo "  │       └── intro/"
echo "  │           └── index.html"
echo "  └── assets/                       # Shared assets"
echo ""

echo "🔗 URL Mapping Rules:"
echo "  ┌─────────────────────────┬──────────────────────┐"
echo "  │ Source File             │ Generated URL        │"
echo "  ├─────────────────────────┼──────────────────────┤"
echo "  │ docs/intro.md           │ /documentation/intro/ │"
echo "  │ i18n/es/.../intro.md    │ /es/documentation/intro/ │"
echo "  │ i18n/de/.../intro.md    │ /de/documentation/intro/ │"
echo "  │ i18n/fr/.../intro.md    │ /fr/documentation/intro/ │"
echo "  └─────────────────────────┴──────────────────────┘"
echo ""

echo "🌐 Why No /en/ Prefix:"
echo "  • English is the default locale"
echo "  • Docusaurus treats default as 'root'"
echo "  • /documentation/ = English version"
echo "  • /es/documentation/ = Spanish version"
echo "  • /de/documentation/ = German version"
echo ""

echo "⚙️ Build Process:"
echo "  1. Parse all .md files in docs/"
echo "  2. Parse all .md files in i18n/*/docs/"
echo "  3. Generate HTML for each locale"
echo "  4. Create static file structure"
echo "  5. Add client-side routing for SPA behavior"
echo ""

echo "🚀 Deployment Ready:"
echo "  • All files are static HTML"
echo "  • Works on GitHub Pages, Netlify, Vercel"
echo "  • No server required"
echo "  • Fast loading with CDN caching"
echo ""

echo "📝 To Test Build:"
echo "  cd apps/docs"
echo "  npm run build"
echo "  # Check build/ directory structure"
echo ""
