#!/bin/bash

echo "🎯 Language Switcher - Section-Specific Behavior"
echo "=============================================="
echo ""

echo "📍 Custom Behavior ONLY for /documentation:"
echo "  • Path: /documentation/ or /documentation"
echo "  • Override: ✅ Applied"
echo "  • URL Generation: /documentation/?locale=es"
echo "  • Translation: URL-based JSON files"
echo "  • Language Switcher: Custom (URL parameters)"
echo ""

echo "📍 Normal Docusaurus Behavior for /docs:"
echo "  • Path: /docs/ or /docs/*"
echo "  • Override: ❌ Not applied"
echo "  • URL Generation: /es/docs/intro"
echo "  • Translation: Docusaurus i18n"
echo "  • Language Switcher: Normal (path-based)"
echo ""

echo "🔄 Logic Flow:"
echo "  if (pathname === '/documentation/' || pathname === '/documentation') {"
echo "    // Apply custom behavior"
echo "    Override language switcher click"
echo "    Generate: /documentation/?locale=es"
echo "  } else {"
echo "    // Let Docusaurus handle normally"
echo "    No override applied"
echo "    Generate: /es/docs/intro (normal)"
echo "  }"
echo ""

echo "🌐 User Experience:"
echo "  Main Section (/documentation/):"
echo "    • User clicks language switcher → /documentation/?locale=es"
echo "    • URL parameter detection → JSON translation"
echo "    • Content updates in place"
echo ""
echo "  Docs Section (/docs/):"
echo "    • User clicks language switcher → /es/docs/intro"
echo "    • Docusaurus i18n → Path-based translation"
echo "    • Page redirects to localized version"
echo ""

echo "✅ Benefits:"
echo "  • ✅ Main section: Clean URLs with parameters"
echo "  • ✅ Docs section: Normal Docusaurus i18n"
echo "  • ✅ No broken URLs anywhere"
echo "  • ✅ Proper separation of concerns"
echo "  • ✅ Users can switch languages in both sections"
echo ""

echo "🚀 Final Result:"
echo "  • /documentation → Custom URL parameter switching"
echo "  • /docs → Normal Docusaurus path-based switching"
echo "  • Both work perfectly for their respective sections"
echo ""

echo "✅ Section-specific language switcher behavior implemented!"
